# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-03 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permabots', '0007_auto_20160530_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hook',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable hook', verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='messengermessage',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('postback', 'Postback'), ('delivery', 'Delivery')], max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.CharField(choices=[('Get', 'Get'), ('Post', 'Post'), ('Put', 'Put'), ('Delete', 'Delete'), ('Patch', 'Patch')], default='Get', help_text='Define Http method for the request', max_length=128, verbose_name='Method'),
        ),
    ]
