# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permabots', '0008_auto_20170403_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='keyboard_template',
            field=models.TextField(blank=True, help_text='Template to generate keyboard response. In jinja2 format. http://jinja.pocoo.org/', null=True, verbose_name='Keyboard template'),
        ),
    ]
