# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import permabots.validators


class Migration(migrations.Migration):

    dependencies = [
        ('permabots', '0009_auto_20170403_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='custom_payload',
            field=models.TextField(blank=True, null=True, verbose_name='custom payload'),
        ),
        migrations.AlterField(
            model_name='response',
            name='keyboard_template',
            field=models.TextField(blank=True, help_text='Template to generate keyboard response. In jinja2 format. http://jinja.pocoo.org/', null=True, validators=[permabots.validators.validate_template, permabots.validators.validate_telegram_keyboard], verbose_name='Keyboard template'),
        ),
    ]
